services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: merchstoredb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d merchstoredb'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/merchstoredb?sslmode=disable"
      JWT_SECRET: "secret"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      
volumes:
  db-data:

networks:
  internal:
